### ISSUE TITLE
Reconsider misc extension encoding scheme

### ISSUE THREAD

**Issue by jrtc27** [riscv/riscv-acpi#3]
8 bits per sub-extension seems extremely wasteful when only 16 bits are available. It may also be better to just pack things more tightly; especially things like Sstc and Sscoff don't need their own group, but the same is true of most of the Z* sub-groups. If you want to only have 16 bits per extension then you really need to be very careful not to waste those bits and dig yourself a hole for the future that requires a new table version and all the pain that comes with it.

**Comment by vlsunil** [comment]
Yes, I agree we should reduce the wastage and avoid new version of the table atleast for 5-10 years. This was the initial proposal I had. But later I realized the tech-config group is going to define the schema grouping  extensions. I am waiting for it to be frozen so that ACPI tables will be aligned with it.
May be just unpriv, supervisor, machine, hypervisor and custom groups are sufficient(max 4 bits) and 12 bits for extensions. But let me wait till config group freezes the schema. Thank you very much!

**Comment by vlsunil** [comment]
latest proposal is to keep entire ISA string in the ACPI table so that most part of the in the OS works for both DT and ACPI. Also, it has advantage of not updating any tables for any new extension. So, the old proposal is no longer valid and hence closing this issue with the old proposal
